
use customer_shooping_behaviour
select * from df_customer_shopping_behavior
--Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM([purchase_amount_(usd)]) as total_revenue
from df_customer_shopping_behavior
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,[purchase_amount_(usd)]
from df_customer_shopping_behavior
where discount_applied = 'Yes' and [purchase_amount_(usd)] >= (select AVG([purchase_amount_(usd)]) from df_customer_shopping_behavior)


-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,AVG(review_rating::numeric) as avg_review_rating
from df_customer_shopping_behavior
group by item_purchased
order by avg_review_rating

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select AVG([purchase_amount_(usd)]) as avg_amount,shipping_type
from df_customer_shopping_behavior
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,AVG([purchase_amount_(usd)]) as Avg_spend,SUM([purchase_amount_(usd)]) as total_revenue
from df_customer_shopping_behavior
group by subscription_status
order by Avg_spend,total_revenue desc


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select TOP 5
    item_purchased,
    ROUND(
        100.0 * SUM(case when discount_applied = 'Yes' then 1 else 0 end) 
        / COUNT(*),2 ) as discount_rate
from df_customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate desc;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
select customer_id,previous_purchases,
case
 when previous_purchases = 1 then 'New'
 when previous_purchases between 2 and 10 then 'Returning'
 Else 'Loyal'
 End as customer_segment
from df_customer_shopping_behavior
 )
 select customer_segment,COUNT(*) as segment_count
 from customer_type
 group by customer_segment
 order by segment_count  desc


--Q8. What are the top 3 most purchased products within each category? 
with item_counts as(
    select
        category,
        item_purchased,
        count(customer_id) as total_orders,
        row_number() over (
            partition by category 
            order by  COUNT(customer_id) desc
        ) as item_rank
    from df_customer_shopping_behavior
    group by category, item_purchased
)
select
    item_rank,
    category,
    item_purchased,
    total_orders
from item_counts
where item_rank <= 3
order by category, item_rank;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from df_customer_shopping_behavior
where previous_purchases > 5 
group by subscription_status

--Q10. What is the revenue contribution of each age group? 
select SUM([purchase_amount_(usd)]) as Total_revnue,age_group
from df_customer_shopping_behavior
group by age_group
order by Total_revnue desc